name: wechat_scan
description: wechat_scan
publish_to: "none"
version: 1.0.0
environment:
  sdk: ">=3.0.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  url_launcher: ^6.1.8
  wechat_assets_picker: ^8.5.0
  qrscan: ^0.3.3
  mobile_scanner: ^3.2.0
  vibration: ^1.7.7
  qr_flutter: ^4.1.0
  image_gallery_saver_v3: ^1.0.0
  flutter_easyloading: ^3.0.5
  camera: ^0.10.5+2
  http: ^0.13.6
  crypto: ^3.0.3
  connectivity_plus: ^4.0.1
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
